export const ADD_MOVIE = "ADD_MOVIE";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const GET_MOVIE_DELETE = "GET_MOVIE_DELETE";
export const DELETED_SUCCESS = "DELETED_SUCCESS";
export const DELETED_ERROR = "DELETED_ERROR";

export const GET_MOVIE_SWITCH = "GET_MOVIE_SWITCH";

export const START_EDITION_SWITCH = "START_EDITION_SWITCH";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_ERROR = "EDIT_ERROR";
